alter system flush buffer_cache;
alter system flush shared_pool;
set autotrace traceonly statistics;

timing start no_col_tables;

INSERT INTO SALES_OUTLET_COL (ID, SQUARE_FEET, ADDRESS, CITY, PROVINCE, TELEPHONE, POSTAL_CODE, LONGITUDE, LATITUDE, SALES_OUTLET_TYPE_ID, MANAGER_STAFF_ID) 
VALUES (
10001,
1200,
'Kazimierza Wielkiego 20',
'Wroclaw',
'PL',
'520-153-0843',
50231,
-110.9845,
32.2691,
1,
606);

INSERT INTO sales_outlet_target (id, target_date, product_id, total_goal, sales_outlet_id)
VALUES(10001, to_date('21.03.2017', 'DD.MM.RRRR'), 1081, 1780, 10001);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (20001, 'Jakub', 'Stepaniak', CURRENT_DATE, 10001, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (20002, 'Grzegorz', 'Stala', CURRENT_DATE, 10001, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (20003, 'Szymon', 'Konopka', CURRENT_DATE, 10001, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (20004, 'Jan', 'Kowalski', CURRENT_DATE, 10001, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (20005, 'Adam', 'Nowak', CURRENT_DATE, 10001, 3);

rollback;
    
timing stop;

timing start col_tables; 

INSERT INTO SALES_OUTLET (ID, SQUARE_FEET, ADDRESS, CITY, PROVINCE, TELEPHONE, POSTAL_CODE, LONGITUDE, LATITUDE, SALES_OUTLET_TYPE_ID, MANAGER_STAFF_ID) 
VALUES (
10000,
1200,
'Kazimierza Wielkiego 20',
'Wroclaw',
'PL',
'520-153-0843',
50231,
-110.9845,
32.2691,
1,
606);

INSERT INTO sales_outlet_target (id, target_date, product_id, total_goal, sales_outlet_id)
VALUES(10000, to_date('21.03.2017', 'DD.MM.RRRR'), 1081, 1780, 10000);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (10000, 'Jakub', 'Stepaniak', CURRENT_DATE, 10000, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (10001, 'Grzegorz', 'Stala', CURRENT_DATE, 10000, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (10002, 'Szymon', 'Konopka', CURRENT_DATE, 10000, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (10003, 'Jan', 'Kowalski', CURRENT_DATE, 10000, 3);

INSERT INTO STAFF (ID, FIRST_NAME, LAST_NAME, START_DATE, SALES_OUTLET_ID, POSITION_ID) 
VALUES (10004, 'Adam', 'Nowak', CURRENT_DATE, 10000, 3);

rollback;

timing stop;

EXIT;


