-- ZESTAW SZYMON KONOPKA

-- ZESTAW GRZEGORZ STALA

-- QUERY 1
select G.GENERATIONNAME, AVG(S.LINEITEMAMOUNT) from CUSTOMER C
    join GENERATION G on C.BIRTHYEAR = G.BIRTHYEAR
    join SALESRECIEPTS S on C.ID = S.CUSTOMER
group by G.GENERATIONNAME;

-- QUERY 3
select * from (
select P.ID, P.PRODUCTCATEGORY, PY.WASTEPERCENTAGE, D.TRANSACTIONDATE, 'GOOD' from GRZEGORZ.PRODUCT P
    join GRZEGORZ.PASTRYINVENTORY PY on P.ID = PY.PRODUCT
    join DATES D on PY.TRANSACTIONDATE = D.TRANSACTIONDATE
    order BY PY.WASTEPERCENTAGE) res1 where res1.TRANSACTIONDATE < to_date('05-04-19','DD-MM-YY') AND ROWNUM <= 10
union
select * from (
select P.ID, P.PRODUCTCATEGORY, PY.WASTEPERCENTAGE, D.TRANSACTIONDATE, 'BAD' from GRZEGORZ.PRODUCT P
    join GRZEGORZ.PASTRYINVENTORY PY on P.ID = PY.PRODUCT
    join DATES D on PY.TRANSACTIONDATE = D.TRANSACTIONDATE
    order BY PY.WASTEPERCENTAGE DESC) res2  where res2.TRANSACTIONDATE < to_date('05-04-19','DD-MM-YY') AND ROWNUM <= 10;

-- ZESTAW JAKUB STEPANIAK