CREATE OR REPLACE DIRECTORY ext_tab_dir as 'D:\projects\advanced-databases\data\new_dataset';

CREATE TABLE sales_receipt_tests (
    id number(10) GENERATED BY DEFAULT AS IDENTITY, 
    transaction_datetime timestamp NOT NULL, 
    in_store number NOT NULL, 
    "order" number(10) NOT NULL, 
    line_item_id number(10) NOT NULL, 
    quantity number(10) NOT NULL, 
    line_item_amount number(10, 2) NOT NULL, 
    unit_price number(10, 2) NOT NULL, 
    promo number NOT NULL, 
    sales_outlet_id number(10), 
    staff_id number(10) NOT NULL, 
    customer_id number(10), 
    product_id number(10) NOT NULL, 
    PRIMARY KEY (id)
);

TIMING START load_sample_insert_timing;

INSERT INTO sales_receipt_tests (transaction_datetime, in_store, "order", line_item_id, quantity, line_item_amount, unit_price, promo, sales_outlet_id, staff_id, customer_id, product_id)
SELECT transaction_datetime_ext, in_store_ext, order_ext, line_item_id_ext, quantity_ext, line_item_amount_ext, unit_price_ext, promo_ext, sales_outlet_id_ext, staff_id_ext, customer_id_ext, product_id_ext
FROM EXTERNAL (   
    (id_ext number(10) NOT NULL, 
     transaction_datetime_ext timestamp NOT NULL, 
     in_store_ext number NOT NULL, 
     order_ext number(10) NOT NULL, 
     line_item_id_ext number(10) NOT NULL, 
     quantity_ext number(10) NOT NULL, 
     line_item_amount_ext number(10, 2) NOT NULL, 
     unit_price_ext number(10, 2) NOT NULL, 
     promo_ext number NOT NULL, 
     sales_outlet_id_ext number(10) NOT NULL, 
     staff_id_ext number(10) NOT NULL, 
     customer_id_ext number(10), 
     product_id_ext number(10) NOT NULL)     
    TYPE ORACLE_LOADER     
    DEFAULT DIRECTORY ext_tab_dir
    ACCESS PARAMETERS (
      RECORDS DELIMITED BY '\n'
      FIELDS TERMINATED BY ';' (
        id_ext, 
        transaction_datetime_ext CHAR(20) DATE_FORMAT DATE MASK "yyyy.mm.dd HH24:MI:SS", 
        in_store_ext, 
        order_ext, 
        line_item_id_ext, 
        quantity_ext, 
        line_item_amount_ext, 
        unit_price_ext, 
        promo_ext, 
        sales_outlet_id_ext, 
        staff_id_ext, 
        customer_id_ext, 
        product_id_ext))     
   LOCATION ('sales_receipt.csv') REJECT LIMIT UNLIMITED) sales_receipt_external;    

TIMING STOP;
EXIT ROLLBACK;
/