CREATE TABLE sales_outlet_xml (
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    square_feet NUMBER(10) NOT NULL,
    address VARCHAR2(512) NOT NULL,
    city VARCHAR2(256) NOT NULL,
    province VARCHAR2(256) NOT NULL,
    telephone VARCHAR2(128) NOT NULL,
    postal_code NUMBER(10) NOT NULL,
    longitude FLOAT(10) NOT NULL,
    latitude FLOAT(10) NOT NULL,
    sales_outlet_type_id NUMBER(10) NOT NULL,
    manager_staff_id NUMBER(10),
    sales_targets XMLTYPE,
    PRIMARY KEY (ID)
);
