CREATE TABLE sales_outlet_xml (
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    square_feet NUMBER(10) NOT NULL,
    address VARCHAR2(512) NOT NULL,
    city VARCHAR2(256) NOT NULL,
    province VARCHAR2(256) NOT NULL,
    telephone VARCHAR2(128) NOT NULL,
    postal_code NUMBER(10) NOT NULL,
    longitude FLOAT(10) NOT NULL,
    latitude FLOAT(10) NOT NULL,
    sales_outlet_type_id NUMBER(10) NOT NULL,
    manager_staff_id NUMBER(10),
    sales_targets XMLTYPE,
    PRIMARY KEY (ID)
);

INSERT INTO SALES_OUTLET_XML (ID, SQUARE_FEET, ADDRESS, CITY, PROVINCE, TELEPHONE, POSTAL_CODE, LONGITUDE, LATITUDE, SALES_OUTLET_TYPE_ID, MANAGER_STAFF_ID, SALES_TARGETS) 
VALUES (1, 1733, '2139 Orin Plaza', 'Tucson', 'AZ', '520-153-0843', 85705, -110.9845, 32.2691, 1, 606, '<?xml version="1.0" encoding="UTF-8"?>
<sales_targets>
  <sales_target>
    <target_date>14-SEP-19</target_date>
    <product_id>4635</product_id>
    <total_goal>2061</total_goal>
  </sales_target>
</sales_targets>');

select so.sales_targets.extract('/sales_targets/sales_target/target_date/text()').getstringval()
from sales_outlet_xml so
