DROP TABLE customer_xml;
CREATE TABLE customer_xml (
	id number(10) GENERATED BY DEFAULT AS IDENTITY, 
	full_name varchar2(128) NOT NULL, 
	email varchar2(256) NOT NULL, 
	since date NOT NULL, 
	loyalty_card_number varchar2(16) NOT NULL, 
	birth_date date NOT NULL, 
	gender varchar2(1) NOT NULL, 
	home_sales_outlet_id number(10), 
	generation_id number(10) NOT NULL, 
	age_details XMLType,
	PRIMARY KEY (id)
);

INSERT INTO customer_xml (id, full_name, email, since, loyalty_card_number, birth_date, gender, home_sales_outlet_id, generation_id, age_details)
VALUES (1, 'Szymon Konopka', 'szymonkonopka@gmail.com', TO_DATE('21.3.2017', 'DD.MM.YYYY'), 640-354-4198, TO_DATE('27.3.2007', 'DD.MM.YYYY'), 'M', 128, 2, '<?xml version="1.0" encoding="UTF-8"?>
	<age_details>
	<birth_date>09-DEC-96</birth_date>
	<generation>Baby Boomers</generation>
	</age_details>'
);

SELECT c.age_details.extract('/age_details/age_detail/target_date/text()').getstringval()
FROM customer_xml c;

DROP TABLE customer_xml;

EXIT;