TIMING START create_sr_load_sample;

CREATE TABLE sales_outlet_load_sample (
    id number(10) GENERATED BY DEFAULT AS IDENTITY, 
    square_feet number(10) NOT NULL, 
    address varchar2(512) NOT NULL, 
    city varchar2(256) NOT NULL, 
    province varchar2(256) NOT NULL, 
    telephone varchar2(128) NOT NULL, 
    postal_code number(10) NOT NULL, 
    longitude float(10) NOT NULL, 
    latitude float(10) NOT NULL, 
    sales_outlet_type_id number(10) NOT NULL, 
    manager_staff_id number(10), 
    PRIMARY KEY (id)
);

TIMING STOP;
EXIT ROLLBACK;
/