TIMING START create_sr_load_sample;

CREATE TABLE sales_receipt_load_sample (
    id number(10) GENERATED BY DEFAULT AS IDENTITY, 
    transaction_datetime timestamp NOT NULL, 
    in_store number NOT NULL, 
    "order" number(10) NOT NULL, 
    line_item_id number(10) NOT NULL, 
    quantity number(10) NOT NULL, 
    line_item_amount number(10, 2) NOT NULL, 
    unit_price number(10, 2) NOT NULL, 
    promo number NOT NULL, 
    sales_outlet_id number(10), 
    staff_id number(10) NOT NULL, 
    customer_id number(10), 
    product_id number(10) NOT NULL, 
    PRIMARY KEY (id)
);

TIMING STOP;

DROP TABLE sales_receipt_load_sample;

EXIT ROLLBACK;
/